name: pataya_ending_card
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  
  flutter_keyboard_visibility: ^5.4.0
  flutter_native_splash: ^2.2.19
  google_fonts: ^4.0.3
  image_gallery_saver: ^2.0.2
  universal_io: ^2.2.0
  universal_html: ^2.2.1
  mime: ^1.0.4
  screenshot: ^2.1.0
  share_plus: ^7.0.2
  intl: ^0.18.0
  rename: ^2.0.1
  shared_preferences: ^2.0.13
  logger: ^1.1.0
  path: ^1.8.2
  path_provider: ^2.0.11
  validators: ^3.0.0
  equatable: ^2.0.3
  url_launcher: ^6.1.2
  uuid: ^3.0.7
  faker: ^2.0.0
  collection: ^1.17.0
  loader_overlay: ^2.2.0
  cached_network_image: ^3.2.0
  auto_route: ^7.5.0
  stacked: ^3.2.0
  stacked_generator: ^1.0.0
  stacked_services: ^1.0.0
  stacked_themes: ^0.3.9
  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0
  reactive_forms: ^14.3.0
  reactive_date_time_picker: ^0.6.1
  reactive_forms_annotations: ^1.1.0
 
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^2.3.2



dev_dependencies:
 
  hive_generator: ^2.0.0
  build_runner: ^2.4.5
  reactive_forms_generator: ^1.2.0
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  analyzer:
  auto_route_generator: ^7.1.1
  dependency_validator: ^3.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/
  uses-material-design: true
