name: pataya_ending_card
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.1
  stacked_services: ^1.2.0
  stacked_themes: ^0.3.12
  google_fonts: ^4.0.3
  intl: ^0.18.0
  uuid: ^3.0.7
  collection: ^1.17.0
  freezed_annotation: ^2.0.3
  json_annotation: ^4.8.1
  reactive_forms: ^16.0.0
  reactive_date_time_picker: ^3.0.0
  reactive_forms_annotations: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  responsive_builder: ^0.7.0
  flutter_animate: ^4.2.0
  cached_network_image: ^3.2.0
  flutter_native_splash: ^2.2.19

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.4.0
  hive_generator: ^2.0.0
  reactive_forms_generator: ^4.0.0
  freezed: ^2.3.5
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/images/
  uses-material-design: true

